[build]
  publish = "."

[[headers]]
  for = "/content.json"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/content.en.json"
  [headers.values]
    Cache-Control = "no-store"
